name: Release
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Run gradle tasks [build publishMods]
        uses: gradle/gradle-build-action@v2
        env:
          SNAPSHOT: false
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          arguments: "build publishMods"
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-output
          path: ./**/libs/*.jar